### ISSUE TITLE
Route Detection does not work

### ISSUE THREAD

**Issue by delgermurun** [Meteor-Reaction/Herald#51]
On iron:router@1.0.7.

[this.path](https://github.com/Meteor-Reaction/Herald/blob/master/client/startup.js#L19) is undefined.

**Comment by Kestanous** [comment]
Interesting, looks like that may have been removed from iron:router at some point. I will test this and fix as needed over the next two weeks. Thanks @delgermurun, if you get to it before me PRs are welcome.
