### ISSUE TITLE
Email messages not sending in production (Telescope)

### ISSUE THREAD

**Issue by jshimko** [Meteor-Reaction/Herald#53]
I've been struggling for several days to find a reason why my notification emails are not sending in my Telescope-based app.  I threw a ton of console.log's in the code and narrowed it down to Herald being successfully called [here](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-notifications/lib/notifications.js#L16) (in the case of a new post email notification), but nothing in [this block](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-notifications/lib/herald.js#L49-L61) ever runs.  It's like the notification get queued and then never happens.  No errors or logs on client or server.

This only seems to happen in production (Modulus, AWS, DO all have the same symptom).  This also reliably happens with a completely untouched fresh copy of [Telescope](https://github.com/TelescopeJS/Telescope).

I'm completely out of ideas at this point.  Any suggestions?

**Comment by Kestanous** [comment]
@jshimko gah, I thought I had fixed this a while back! Ok I will look at it. Thanks for bring this here and sorry for all the trouble. I think I need to remove the queue and find a different option. For your problem please look at https://github.com/artwells/meteor-queue/. Likely you have a ton of errors in `Queue.log.find().fetch()` 

As to why it seems like it never runs, the queue squashes console logs...

**Comment by Kestanous** [comment]
@Meteor-Reaction/herald any thoughts on this? As a quick option we could switch to cfs:power-queue, it looks like it does not squash console logging.

**Comment by erasaur** [comment]
I was looking into cfs:power-queue as an option as well. Havent yet played around with it though.

**Comment by Kestanous** [comment]
We shoot! http://power-queue-test.meteor.com/ ok I will look into adding that after I test manually test master. This should be a pleasant improvement. 

@jshimko if I don't get this up today I will not be able to until Sunday or later, if you or anyone wants to speed this up feel free to do a PR.

@erasaur I know it does not solve our interval timeout issue but at least is an improvement. If your free lets work on v2 some next week.

**Comment by dohomi** [comment]
Hey guys, 
I haven't had any problems with the current state of herald, all the emailing was running fine for me. But as meteor-queue is blowing the database I have nothing against the cfs package!
Cheers

**Comment by jshimko** [comment]
Hey @Kestanous, thanks for the heads up on the logs.  I checked the queuelog collection and there were 30,000+ documents inserted in a span of 5 days.  I obviously didn't look at all of them, but it appeared to just be the following two documents over and over...

```
{
  "command" : "Queue.run failed due to locking query.run",
  "status" : "lockfailed",
  "created_at" : ISODate("2015-02-01T04:57:30.496Z"),
  "_id" : "ukh8qERDyNzSXLA8H"
}

{
  "command" : "Queue.add failed query.run",
  "status" : "lockfailed",
  "data" : "E11000 duplicate key error index: dataforgood_io.queue.$lock_name_1  dup key: { : \"query.run\" }",
  "created_at" : ISODate("2015-02-01T04:57:30.492Z"),
  "_id" : "Yb3bnZ4NfvFHdsi32"
}
```

Not surprisingly, there were hundreds of emails with pending status in the queue.  I cleared out all the documents in the queue and queuelog collections and we're now back up and running with email notifications.  I've been monitoring for new errors and haven't seen any yet (2 days so far).  Not sure I've actually fixed anything, but now I at least know where to look if this ever happens again.  Wish I figured that out before spending almost two entire days trying 50 other things.  :)

Any idea what may have caused the lockup after seeing the above errors?  I'd be happy to submit an issue over at the meteor-queue repo, but I'd like to figure out if either the Herald package or my code caused it first.

Thoughts?

**Comment by Kestanous** [comment]
Unfortunately I never pushed the queue that hard so I am not sure. That said since Herald still uses artwells:queue v0.0.3 it may have come from this: https://github.com/artwells/meteor-queue/issues/5. 

I will update Herald to v0.0.4 regardless. At least until I have a chance to look at power queue in more depth.

**Comment by Kestanous** [comment]
@jshimko looks like the queue update has not been published. I will look into what it will take to switch to power queue now.

**Comment by Kestanous** [comment]
Looks like power queue can not handle delayed jobs... that takes it out of the list of options.

**Comment by SachaG** [comment]
Could we make queuing an optional opt-in feature in Herald? I feel like until it's actually useful, it's probably going to be more trouble than it's worth. 

I'm not talking about removing it completely, just adding a setting of some kind that lets you bypass it and send notifications directly?

**Comment by SachaG** [comment]
I'm still hearing from people with notification issues. I really think we should have a way to disable queuing until we have a better way of making sure it actually works…

**Comment by Kestanous** [comment]
@SachaG Sorry I had thought I responded to this. Yes I am in agreement, how does this sound. 

1. herald makes it dependency on artwells:queue weak and only uses it if its available.

2. you add artwells:queue to telescope

3. you add a depreciation warning that you plan on removing artwells:queue in a few more releases give instructions how to do that now (remove the package and delete the two queue collections). 

@Meteor-Reaction/herald any issues with this?

**Comment by Kestanous** [comment]
This is completely untested but the fix should be done in: https://github.com/Meteor-Reaction/Herald/tree/remove_artwells_queue. I may not get a chance to properly test / build tests for a few days. If anyone tests it please let me know, thanks!

**Comment by SachaG** [comment]
Looks good to me, thanks! I think in Telescope's case, I'll probably just not use artwells:queue at all by default. Not sure it needs a deprecation warning?

**Comment by dohomi** [comment]
Hi guys,
+1 for week dependency. We would need another package the queue is not reliable. In my app there is every now and then a blocking queue task which holding back the sendout for all following.

**Comment by Kestanous** [comment]
I apologize to all who this effected, the queue was a bad call on my end.

@dohomi do you have proper testing in your app? Can you confirm that this branch fixes the issue? 

@SachaG I guess that is not necessary. When you update Telescope would you please make a note about how the queue has been removed and how users should delete the queue collections? I don't want users to be running around with deprecated data in their DB.

**Comment by jshimko** [comment]
I suppose you could just empty out those collections with a new migration.   A lot of users may not be comfortable with having to mess with mongo.  All they'd have to do is make sure the queue package is removed.  And everyone else that is comfortable enough could delete the collections entirely.

**Comment by jshimko** [comment]
Sorry, I guess I should clarify since we're in a different repo here.  I specifically meant migrations in Telescope.  :)

**Comment by dohomi** [comment]
Hi @Kestanous I will test it tomorrow in my app. Let you know asap! Cheers
