### ISSUE TITLE
Custom Medium

### ISSUE THREAD

**Issue by zimt28** [Meteor-Reaction/Herald#59]
Is there a way to define custom media? I want to show notifications on the client using [noty](http://ned.im/noty/). The `onsite` medium will not work, as noty uses JavaScript syntax to generate notifications.

**Comment by zimt28** [comment]
Looks like I can just use [addRunner](https://github.com/Meteor-Reaction/Herald#addrunner), simple :)

**Comment by Kestanous** [comment]
@zimt28 looks like you found it ^_^ if you build something nice feel free to package it and publish to atmo. If you have any other questions let me know.
